name: Build and Deploy Web 2.0

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - "**/*.md"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: dhbw_tif23_betriebmonitor-web2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Web2.0/Dockerfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r ./Web2.0/requirements.txt

      - name: Static analysis
        run: python -m compileall ./Web2.0/server.py

      - name: Prepare image tags
        id: prep
        run: |
          owner="${{ github.repository_owner }}"
          owner_lower=$(printf '%s' "$owner" | tr '[:upper:]' '[:lower:]')
          echo "owner=$owner_lower" >> "$GITHUB_OUTPUT"
          echo "latest=$owner_lower/${IMAGE_NAME}:latest" >> "$GITHUB_OUTPUT"
          echo "sha=$owner_lower/${IMAGE_NAME}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: ./Web2.0
          file: ./Web2.0/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.prep.outputs.latest }}
            ghcr.io/${{ steps.prep.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        
      - name: Validate compose configuration
        run: |
          if [ -f "docker-compose.yml" ]; then
            docker compose -f docker-compose.yml config --quiet
          else
            echo "No docker-compose.yml found in repository root, skipping validation"
          fi
