name: Build Docker Image

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — Set up Docker Buildx (for better caching and multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3 — Login to GitHub Container Registry (ghcr.io)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4 — Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner,, }}/bank-upstash-demo:latest


      # Step 5 — Verify image built successfully
      - name: Verify image
        run: docker images ghcr.io/${{ github.repository_owner }}/bank-upstash-demo:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bank-upstash-demo:latest
            ghcr.io/${{ github.repository_owner }}/bank-upstash-demo:${{ github.sha }}
